name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout del código
        uses: actions/checkout@v4

      # Paso 2: Configurar Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Paso 3: Instalar dependencias
      - name: Instalar dependencias
        run: npm install

      # Paso 4: Ejecutar pruebas Cypress y generar reporte Allure
      - name: Ejecutar pruebas Cypress
        run: npm run ejecutar-pruebas
              
      # Paso 5: Guardar reporte Allure como artifact (opcional, para depuración)
      - name: Guardar reporte Allure
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report
      
      # Paso 6: Desplegar reporte Allure a GitHub Pages
      - name: Desplegar reporte Allure a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          keep_files: false